version: '3.8'

services:
  lyrics-status:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-lyrics-status
    restart: unless-stopped
    ports:
      - "8999:8999"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
